services:
  php:
    image: php:8.3-fpm
    restart: always
    working_dir: /var/www
    volumes:
      - ../site:/var/www
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ../site:/var/www
      - ./nginx:/etc/nginx/conf.d