services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php_and_composer
    restart: always
    working_dir: /var/www
    volumes:
      - ../site:/var/www
      - ./php/php-edited.ini:/usr/local/etc/php/php.ini
      
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ../site:/var/www
      - ./nginx:/etc/nginx/conf.d